site_name: Laskewitz.io
theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.tabs
plugins:
  - search
  - tags
nav:
  - Home: 'index.md'
  - Power Platform Connectors: 'connectors/index.md'
  - About: 'about.md'
