site_name: 'Laskewitz.io'
site_url: https://www.laskewitz.io
theme:
  name: material
  logo: images/logo-white.png
  favicon: images/icon.png
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.tabs.link
    - toc.follow
    - toc.integrate
  palette:
    primary: black
    accent: deep orange
nav:
  - About: 'index.md'
  - Events: 'events.md'
  - Power Platform Connectors: 'power-platform-connectors.md'

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
extra:
  generator: false
  social:
    - icon: material/rss
      link: https://laskewitz.io/feed_rss_created.xml
    - icon: material/youtube
      link: https://youtube.com/daniellaskewitz
    - icon: material/twitter
      link: https://twitter.com/laskewitz
    - icon: material/github
      link: https://github.com/laskewitz
    - icon: material/linkedin
      link: https://linkedin.com/in/laskewitz
  consent:
    title: Cookie consent
    description: >-
      I use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of my site and whether users
      find what they're searching for. With your consent, you're helping me to
      make my site better.
plugins:
  - search
  - meta
  - social
extra_css:
  - stylesheets/extra.css
