site_name: Laskewitz.io
theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.tabs
plugins:
  - search
  - social
  - tags
nav:
  - Home: 'index.md'
  - Blog: 'blog/index.md'
  - Tools:
      - Power Platform Connectors: 'connectors/index.md'
