site_name: Daniel Laskewitz
theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/apps
  palette:
    primary: blue
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
plugins:
  - meta
  - search
  - social
  - tags
nav:
  - Home: 'index.md'
  - Blog:
      - 'blog/index.md'
      - 'Categories':
          - Code First: 'blog/category/code-first.md'
          - Power Apps: 'blog/category/power-apps.md'
          - Power Automate: 'blog/category/power-automate.md'
          - Tools: 'blog/category/tools.md'
  - Tools:
      - Power Platform Connectors: 'connectors/index.md'
