/**
 * Copy the flag artwork the register needs out of `@twemoji/svg` and into
 * `src/public/images/flags`.
 *
 * Flag emoji are the one glyph a platform is free to refuse: Windows draws the
 * bare country letters, older Android draws a blank box, and every renderer
 * that does draw them picks its own shape. Shipping the SVGs means the board
 * reads the same everywhere.
 *
 * Twemoji is © Twitter, Inc and other contributors, artwork under CC-BY 4.0.
 *
 * Run with `npm run flags` after adding an event in a new country.
 */
import { copyFileSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const root = path.join(import.meta.dirname, '..')
const source = path.join(root, 'node_modules', '@twemoji', 'svg')
const target = path.join(root, 'src', 'public', 'images', 'flags')

/** Tag sequences for the UK nations, which have no alpha-2 code of their own. */
const OVERRIDES = {
  'GB-ENG': '1f3f4-e0067-e0062-e0065-e006e-e0067-e007f',
  'GB-SCT': '1f3f4-e0067-e0062-e0073-e0063-e0074-e007f',
  'GB-WLS': '1f3f4-e0067-e0062-e0077-e006c-e0073-e007f'
}

function twemojiName(code) {
  if (code in OVERRIDES) return OVERRIDES[code]
  if (!/^[A-Z]{2}$/.test(code)) return undefined
  return [...code]
    .map((c) => (0x1f1e6 + c.charCodeAt(0) - 65).toString(16))
    .join('-')
}

const events = readFileSync(path.join(root, 'src', '.vitepress', 'data', 'events.ts'), 'utf8')
const codes = [...new Set([...events.matchAll(/country: '([^']+)'/g)].map((m) => m[1]))].sort()

const copied = []
const missing = []

for (const code of codes) {
  const name = twemojiName(code)
  if (!name) continue
  try {
    copyFileSync(path.join(source, `${name}.svg`), path.join(target, `${code.toLowerCase()}.svg`))
    copied.push(code)
  } catch {
    missing.push(code)
  }
}

const stale = readdirSync(target)
  .filter((f) => f.endsWith('.svg'))
  .map((f) => f.replace(/\.svg$/, '').toUpperCase())
  .filter((code) => !copied.includes(code))

writeFileSync(
  path.join(root, 'src', '.vitepress', 'data', 'flags.ts'),
  [
    '/* Generated by `npm run flags`. Do not edit by hand. */',
    '',
    '/** Country codes with flag artwork in `public/images/flags`. */',
    'export const FLAG_CODES = new Set([',
    ...copied.map((code) => `  '${code}',`),
    '])',
    ''
  ].join('\n')
)

console.log(`Copied ${copied.length} flags: ${copied.join(', ')}`)
if (missing.length) console.warn(`No Twemoji artwork for: ${missing.join(', ')}`)
if (stale.length) console.warn(`Unused files still in place for: ${stale.join(', ')}`)
